<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <EmbeddedResource Include="**\*.cs" Exclude="bin\**;obj\**" />
    <EmbeddedResource Include="**\README.md" Exclude="bin\**;obj\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlgoLab.Core\AlgoLab.Core.csproj" />
  </ItemGroup>

</Project>
